version: "3.9"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  calc:
    build: ./calc
    depends_on:
      - db
    links:
      - db
    volumes: ['./calc:/app']
  api:
    build: ./api
    depends_on:
      - db
      - calc
    links:
      - db
      - calc
    ports:
      - 80:5001
    volumes: ['./api:/app']
    restart: on-failure